### ISSUE TITLE
Add better error message for incorrect args

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-ruby#3]
I was reading in my app and user credentials via the environment and had an error where `nil` values were being used for clientId, clientSecret, etc. I received the following error message which is confusing. It would be better to have a more explicit error for missing parameters.

**Request:**

I'm sending:

```ruby
rc = RingCentral.new(
  ENV['RINGCENTRAL_CLIENT_ID'],
  ENV['RINGCENTRAL_CLIENT_SECRET'],
  ENV['RINGCENTRAL_SERVER_URL'])

rc.authorize(
  username:  ENV['RINGCENTRAL_USERNAME'],
  extension: ENV['RINGCENTRAL_EXTENSION'],
  password:  ENV['RINGCENTRAL_PASSWORD'])
```

But because the `.env` file isn't being read correctly, this gets translated to:

```ruby
rc = RingCentral.new nil, nil, nil
rc.authorize username:nil, extension:nil, password:nil
```

**Error:**

The `nil` values result in a `addr_port` error which is hard to understand given the inputs don't specifically include a port.

```
Traceback (most recent call last):
	18: from get_ringcentral_extension.rb:16:in `<main>'
	17: from /usr/local/rvm/gems/ruby-2.5.0/gems/ringcentral-sdk-0.8.2/lib/ringcentral.rb:62:in `authorize'
	16: from /usr/local/rvm/gems/ruby-2.5.0/gems/ringcentral-sdk-0.8.2/lib/ringcentral.rb:104:in `post'
	15: from /usr/local/rvm/gems/ruby-2.5.0/gems/faraday-0.15.0/lib/faraday/connection.rb:175:in `post'
	14: from /usr/local/rvm/gems/ruby-2.5.0/gems/faraday-0.15.0/lib/faraday/connection.rb:387:in `run_request'
	13: from /usr/local/rvm/gems/ruby-2.5.0/gems/faraday-0.15.0/lib/faraday/rack_builder.rb:143:in `build_response'
	12: from /usr/local/rvm/gems/ruby-2.5.0/gems/faraday-0.15.0/lib/faraday/request/multipart.rb:15:in `call'
	11: from /usr/local/rvm/gems/ruby-2.5.0/gems/faraday-0.15.0/lib/faraday/request/url_encoded.rb:15:in `call'
	10: from /usr/local/rvm/gems/ruby-2.5.0/gems/faraday-0.15.0/lib/faraday/adapter/net_http.rb:33:in `call'
	 9: from /usr/local/rvm/gems/ruby-2.5.0/gems/faraday-0.15.0/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	 8: from /usr/local/rvm/gems/ruby-2.5.0/gems/faraday-0.15.0/lib/faraday/adapter/net_http.rb:38:in `block in call'
	 7: from /usr/local/rvm/gems/ruby-2.5.0/gems/faraday-0.15.0/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	 6: from /usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:1455:in `request'
	 5: from /usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:910:in `start'
	 4: from /usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:1457:in `block in request'
	 3: from /usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:1464:in `request'
	 2: from /usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:1490:in `transport_request'
	 1: from /usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:1551:in `begin_transport'
/usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:1616:in `addr_port': undefined method `include?' for nil:NilClass (NoMethodError)
```

**Comment by tylerlong** [comment]
It is because the server uri is nil so an http exception is thrown.

Other SDKs, such as the Python / JS also don't check the input args are nil or not. So I think we need to be consistent. Either don't change this behavior or we change them all.
